# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongsstate_ide the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first.id)

ActiveRecord::Base.connection.execute("TRUNCATE states")
ActiveRecord::Base.connection.execute("TRUNCATE cities")

State.destroy_all
City.destroy_all

State.create(name: "Alabama")
State.create(name: "Alaska")
State.create(name: "Arizona")
State.create(name: "Arkansas")
State.create(name: "California")
State.create(name: "Colorado")
State.create(name: "Connecticut")
State.create(name: "Delaware")
State.create(name: "Florida")
State.create(name: "Georgia")
State.create(name: "Hawaii")
State.create(name: "Idaho")
State.create(name: "Illinois")
State.create(name: "Indiana")
State.create(name: "Iowa")
State.create(name: "Kansas")
State.create(name: "Kentucky")
State.create(name: "Louisiana")
State.create(name: "Maine")
State.create(name: "Maryland")
State.create(name: "Massachusetts")
State.create(name: "Michigan")
State.create(name: "Minnesota")
State.create(name: "Mississippi")
State.create(name: "Missouri")
State.create(name: "Montana")
State.create(name: "Nebraska")
State.create(name: "Nevada")
State.create(name: "New Hampshire")
State.create(name: "New Jersey")
State.create(name: "New Mexico")
State.create(name: "New York")
State.create(name: "North Carolina")
State.create(name: "North Dakota")
State.create(name: "Ohio")
State.create(name: "Oklahoma")
State.create(name: "Oregon")
State.create(name: "Pennsylvania")
State.create(name: "Rhode Island")
State.create(name: "South Carolina")
State.create(name: "South Dakota")
State.create(name: "Tennessee")
State.create(name: "Texas")
State.create(name: "Utah")
State.create(name: "Vermont")
State.create(name: "Virginia")
State.create(name: "Washington")
State.create(name: "West Virginia")
State.create(name: "Wisconsin")
State.create(name: "Wyoming")


City.create(name: "Auburn", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Montgomery", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Huntsville", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Beatrice", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Birmingham", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Tuscaloosa", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Hoover", state_id: State.where(name: "Alabama").first.id)
City.create(name: "Florence", state_id: State.where(name: "Alabama").first.id)

City.create(name: "Anchorage", state_id: State.where(name: "Alaska").first.id)
City.create(name: "Fairbanks", state_id: State.where(name: "Alaska").first.id)
City.create(name: "Juneau", state_id: State.where(name: "Alaska").first.id)
City.create(name: "Badger", state_id: State.where(name: "Alaska").first.id)
City.create(name: "Knik-Fairview", state_id: State.where(name: "Alaska").first.id)
City.create(name: "College", state_id: State.where(name: "Alaska").first.id)
City.create(name: "North Lakes", state_id: State.where(name: "Alaska").first.id)
City.create(name: "Tanaina", state_id: State.where(name: "Alaska").first.id)

City.create(name: "Phoenix", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Tucson", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Mesa", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Chandler", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Scottsdale", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Glendale", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Gilbert", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Tempe", state_id: State.where(name: "Arizona").first.id)
City.create(name: "Peoria", state_id: State.where(name: "Arizona").first.id)

City.create(name: "Little Rock", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Fort Smith", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Fayetteville", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Springdale", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Jonesboro", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Rogers", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Conway", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "North Little Rock", state_id: State.where(name: "Arkansas").first.id)
City.create(name: "Bentonville", state_id: State.where(name: "Arkansas").first.id)

City.create(name: "Los Angeles", state_id: State.where(name: "California").first.id)
City.create(name: "San Francisco", state_id: State.where(name: "California").first.id)
City.create(name: "San Diego", state_id: State.where(name: "California").first.id)
City.create(name: "Oakland", state_id: State.where(name: "California").first.id)
City.create(name: "San Jose", state_id: State.where(name: "California").first.id)
City.create(name: "Fresno", state_id: State.where(name: "California").first.id)
City.create(name: "Sacramento", state_id: State.where(name: "California").first.id)
City.create(name: "Long Beach", state_id: State.where(name: "California").first.id)
City.create(name: "Bakersfield", state_id: State.where(name: "California").first.id)
City.create(name: "Anaheim", state_id: State.where(name: "California").first.id)

City.create(name: "Oakland", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Denver", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Aurora", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Colorado Springs", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Aurora", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Fort Collins", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Lakewood", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Thornton", state_id: State.where(name: "Colorado").first.id)
City.create(name: "Westminster", state_id: State.where(name: "Colorado").first.id)

City.create(name: "Bridgeport", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "New Haven", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "Stamford", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "Hartford", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "Waterbury", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "Norwalk", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "Danbury", state_id: State.where(name: "Connecticut").first.id)
City.create(name: "New Britain", state_id: State.where(name: "Connecticut").first.id)

City.create(name: "Wilmington", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Dover", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Newark", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Middletown", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Bear", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Glasgow", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Hockessin", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Brookside", state_id: State.where(name: "Delaware").first.id)
City.create(name: "Milford", state_id: State.where(name: "Delaware").first.id)

City.create(name: "Jacksonville", state_id: State.where(name: "Florida").first.id)
City.create(name: "Miami", state_id: State.where(name: "Florida").first.id)
City.create(name: "Tampa", state_id: State.where(name: "Florida").first.id)
City.create(name: "Orlando", state_id: State.where(name: "Florida").first.id)
City.create(name: "St. Petersburg", state_id: State.where(name: "Florida").first.id)
City.create(name: "Hialeah", state_id: State.where(name: "Florida").first.id)
City.create(name: "Port St. Lucie", state_id: State.where(name: "Florida").first.id)
City.create(name: "Tallahassee", state_id: State.where(name: "Florida").first.id)
City.create(name: "Cape Coral", state_id: State.where(name: "Florida").first.id)
City.create(name: "Fort Lauderdale", state_id: State.where(name: "Florida").first.id)

City.create(name: "Atlanta", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Augusta-Richmond County", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Columbus", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Macon-Bibb County", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Savannah", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Athens-Clarke County", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Sandy Springs", state_id: State.where(name: "Georgia").first.id)
City.create(name: "South Fulton", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Johns Creek", state_id: State.where(name: "Georgia").first.id)
City.create(name: "Roswell", state_id: State.where(name: "Georgia").first.id)

City.create(name: "Honolulu", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Hilo", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Pearl City", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Waipahu", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Kailua", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Mililani Town", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Ewa Gentry", state_id: State.where(name: "Hawaii").first.id)
City.create(name: "Kahului", state_id: State.where(name: "Hawaii").first.id)

City.create(name: "Boise City", state_id: State.where(name: "Idaho").first.id)
City.create(name: "Meridian", state_id: State.where(name: "Idaho").first.id)
City.create(name: "Nampa", state_id: State.where(name: "Idaho").first.id)
City.create(name: "Idaho Falls", state_id: State.where(name: "Idaho").first.id)
City.create(name: "Caldwell", state_id: State.where(name: "Idaho").first.id)

City.create(name: "Chicago", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Aurora", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Naperville", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Rockford", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Joliet", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Springfield", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Elgin", state_id: State.where(name: "Illinois").first.id)
City.create(name: "Peoria", state_id: State.where(name: "Illinois").first.id)

City.create(name: "Indianapolis", state_id: State.where(name: "Indiana").first.id)
City.create(name: "Fort Wayne", state_id: State.where(name: "Indiana").first.id)
City.create(name: "Evansville", state_id: State.where(name: "Indiana").first.id)
City.create(name: "South Bend", state_id: State.where(name: "Indiana").first.id)
City.create(name: "Carmel", state_id: State.where(name: "Indiana").first.id)
City.create(name: "Fishers", state_id: State.where(name: "Indiana").first.id)
City.create(name: "Bloomington", state_id: State.where(name: "Indiana").first.id)

City.create(name: "Des Moines", state_id: State.where(name: "Iowa").first.id)
City.create(name: "Cedar Rapids", state_id: State.where(name: "Iowa").first.id)
City.create(name: "Davenport", state_id: State.where(name: "Iowa").first.id)
City.create(name: "Sioux City", state_id: State.where(name: "Iowa").first.id)
City.create(name: "Iowa City", state_id: State.where(name: "Iowa").first.id)
City.create(name: "Waterloo", state_id: State.where(name: "Iowa").first.id)
City.create(name: "Ames", state_id: State.where(name: "Iowa").first.id)

City.create(name: "Wichita", state_id: State.where(name: "Kansas").first.id)
City.create(name: "Overland Park", state_id: State.where(name: "Kansas").first.id)
City.create(name: "Kansas City", state_id: State.where(name: "Kansas").first.id)
City.create(name: "Lawrence", state_id: State.where(name: "Kansas").first.id)
City.create(name: "Topeka", state_id: State.where(name: "Kansas").first.id)
City.create(name: "Olathe", state_id: State.where(name: "Kansas").first.id)

City.create(name: "Louisville", state_id: State.where(name: "Kentucky").first.id)
City.create(name: "Lexington-Fayette", state_id: State.where(name: "Kentucky").first.id)
City.create(name: "Bowling Green", state_id: State.where(name: "Kentucky").first.id)
City.create(name: "Owensboro", state_id: State.where(name: "Kentucky").first.id)
City.create(name: "Covington", state_id: State.where(name: "Kentucky").first.id)
City.create(name: "Richmond", state_id: State.where(name: "Kentucky").first.id)
City.create(name: "Georgetown", state_id: State.where(name: "Kentucky").first.id)

City.create(name: "New Orleans", state_id: State.where(name: "Louisiana").first.id)
City.create(name: "Baton Rogue", state_id: State.where(name: "Louisiana").first.id)
City.create(name: "Shreveport", state_id: State.where(name: "Louisiana").first.id)
City.create(name: "Metairie", state_id: State.where(name: "Louisiana").first.id)
City.create(name: "Lafayette", state_id: State.where(name: "Louisiana").first.id)
City.create(name: "Lake Charles", state_id: State.where(name: "Louisiana").first.id)
City.create(name: "Bossier City", state_id: State.where(name: "Louisiana").first.id)

City.create(name: "Portland", state_id: State.where(name: "Maine").first.id)
City.create(name: "Lewiston", state_id: State.where(name: "Maine").first.id)
City.create(name: "Bangor", state_id: State.where(name: "Maine").first.id)
City.create(name: "South Portland", state_id: State.where(name: "Maine").first.id)
City.create(name: "Auburn", state_id: State.where(name: "Maine").first.id)
City.create(name: "Biddeford", state_id: State.where(name: "Maine").first.id)
City.create(name: "Sanford", state_id: State.where(name: "Maine").first.id)
City.create(name: "Scarborough", state_id: State.where(name: "Maine").first.id)

City.create(name: "Baltimore", state_id: State.where(name: "Maryland").first.id)
City.create(name: "Columbia", state_id: State.where(name: "Maryland").first.id)
City.create(name: "Germantown", state_id: State.where(name: "Maryland").first.id)
City.create(name: "Silver Spring", state_id: State.where(name: "Maryland").first.id)
City.create(name: "Waldorf", state_id: State.where(name: "Maryland").first.id)
City.create(name: "Ellicott City", state_id: State.where(name: "Maryland").first.id)

City.create(name: "Boston", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "Worcester", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "Springfield", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "Cambridge", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "Lowell", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "Brockton", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "New Bedford", state_id: State.where(name: "Massachusetts").first.id)
City.create(name: "Quincy", state_id: State.where(name: "Massachusetts").first.id)

City.create(name: "Detroit", state_id: State.where(name: "Michigan").first.id)
City.create(name: "Grand Rapids", state_id: State.where(name: "Michigan").first.id)
City.create(name: "Warren", state_id: State.where(name: "Michigan").first.id)
City.create(name: "Sterling Heights", state_id: State.where(name: "Michigan").first.id)
City.create(name: "Ann Arbor", state_id: State.where(name: "Michigan").first.id)

City.create(name: "Minneapolis", state_id: State.where(name: "Minnesota").first.id)
City.create(name: "St. Paul", state_id: State.where(name: "Minnesota").first.id)
City.create(name: "Rochester", state_id: State.where(name: "Minnesota").first.id)
City.create(name: "Duluth", state_id: State.where(name: "Minnesota").first.id)
City.create(name: "Bloomington", state_id: State.where(name: "Minnesota").first.id)
City.create(name: "Brooklyn Park", state_id: State.where(name: "Minnesota").first.id)
City.create(name: "Plymouth", state_id: State.where(name: "Minnesota").first.id)

City.create(name: "Jackson", state_id: State.where(name: "Mississippi").first.id)
City.create(name: "Gulfport", state_id: State.where(name: "Mississippi").first.id)
City.create(name: "Southaven", state_id: State.where(name: "Mississippi").first.id)
City.create(name: "Biloxi", state_id: State.where(name: "Mississippi").first.id)
City.create(name: "Hattiesburg", state_id: State.where(name: "Mississippi").first.id)

City.create(name: "Kansas City", state_id: State.where(name: "Missouri").first.id)
City.create(name: "St. Louis", state_id: State.where(name: "Missouri").first.id)
City.create(name: "Springfield", state_id: State.where(name: "Missouri").first.id)
City.create(name: "Columbia", state_id: State.where(name: "Missouri").first.id)
City.create(name: "Independence", state_id: State.where(name: "Missouri").first.id)

City.create(name: "Billings", state_id: State.where(name: "Montana").first.id)
City.create(name: "Missoula", state_id: State.where(name: "Montana").first.id)
City.create(name: "Great Falls", state_id: State.where(name: "Montana").first.id)
City.create(name: "Bozeman", state_id: State.where(name: "Montana").first.id)
City.create(name: "Butte-Silver Bow", state_id: State.where(name: "Montana").first.id)

City.create(name: "Omaha", state_id: State.where(name: "Nebraska").first.id)
City.create(name: "Lincoln", state_id: State.where(name: "Nebraska").first.id)
City.create(name: "Bellevue", state_id: State.where(name: "Nebraska").first.id)
City.create(name: "Grand Island", state_id: State.where(name: "Nebraska").first.id)
City.create(name: "Kearney", state_id: State.where(name: "Nebraska").first.id)

City.create(name: "Las Vegas", state_id: State.where(name: "Nevada").first.id)
City.create(name: "Henderson", state_id: State.where(name: "Nevada").first.id)
City.create(name: "Reno", state_id: State.where(name: "Nevada").first.id)
City.create(name: "Spring Valley", state_id: State.where(name: "Nevada").first.id)
City.create(name: "Sunrise Manor", state_id: State.where(name: "Nevada").first.id)
City.create(name: "Enterprise", state_id: State.where(name: "Nevada").first.id)

City.create(name: "Manchester", state_id: State.where(name: "New Hampshire").first.id)
City.create(name: "Nashua", state_id: State.where(name: "New Hampshire").first.id)
City.create(name: "Concord", state_id: State.where(name: "New Hampshire").first.id)
City.create(name: "Derry", state_id: State.where(name: "New Hampshire").first.id)
City.create(name: "Dover", state_id: State.where(name: "New Hampshire").first.id)

City.create(name: "Newark", state_id: State.where(name: "New Jersey").first.id)
City.create(name: "Jersey City", state_id: State.where(name: "New Jersey").first.id)
City.create(name: "Paterson", state_id: State.where(name: "New Jersey").first.id)
City.create(name: "Elizabeth", state_id: State.where(name: "New Jersey").first.id)
City.create(name: "Lakewood", state_id: State.where(name: "New Jersey").first.id)

City.create(name: "Albuquerque", state_id: State.where(name: "New Mexico").first.id)
City.create(name: "Las Cruces", state_id: State.where(name: "New Mexico").first.id)
City.create(name: "Rio Rancho", state_id: State.where(name: "New Mexico").first.id)
City.create(name: "Santa Fe", state_id: State.where(name: "New Mexico").first.id)
City.create(name: "Roswell", state_id: State.where(name: "New Mexico").first.id)
City.create(name: "Farmington", state_id: State.where(name: "New Mexico").first.id)
City.create(name: "Carlsbad", state_id: State.where(name: "New Mexico").first.id)

City.create(name: "New York City", state_id: State.where(name: "New York").first.id)
City.create(name: "Hempstead", state_id: State.where(name: "New York").first.id)
City.create(name: "Brookhaven", state_id: State.where(name: "New York").first.id)
City.create(name: "Islip", state_id: State.where(name: "New York").first.id)
City.create(name: "Buffalo", state_id: State.where(name: "New York").first.id)
City.create(name: "Syracuse", state_id: State.where(name: "New York").first.id)

City.create(name: "Charlotte", state_id: State.where(name: "North Carolina").first.id)
City.create(name: "Raleigh", state_id: State.where(name: "North Carolina").first.id)
City.create(name: "Greensboro", state_id: State.where(name: "North Carolina").first.id)
City.create(name: "Durham", state_id: State.where(name: "North Carolina").first.id)
City.create(name: "Winston-Salem", state_id: State.where(name: "North Carolina").first.id)

City.create(name: "Fargo", state_id: State.where(name: "North Dakota").first.id)
City.create(name: "Bismarck", state_id: State.where(name: "North Dakota").first.id)
City.create(name: "Grand Forks", state_id: State.where(name: "North Dakota").first.id)
City.create(name: "Minot", state_id: State.where(name: "North Dakota").first.id)
City.create(name: "West Fargo", state_id: State.where(name: "North Dakota").first.id)

City.create(name: "Columbus", state_id: State.where(name: "Ohio").first.id)
City.create(name: "Cleveland", state_id: State.where(name: "Ohio").first.id)
City.create(name: "Cincinatti", state_id: State.where(name: "Ohio").first.id)
City.create(name: "Toledo", state_id: State.where(name: "Ohio").first.id)
City.create(name: "Akron", state_id: State.where(name: "Ohio").first.id)

City.create(name: "Oklahoma City", state_id: State.where(name: "Oklahoma").first.id)
City.create(name: "Tulsa", state_id: State.where(name: "Oklahoma").first.id)
City.create(name: "Norman", state_id: State.where(name: "Oklahoma").first.id)
City.create(name: "Broken Arrow", state_id: State.where(name: "Oklahoma").first.id)
City.create(name: "Edmond", state_id: State.where(name: "Oklahoma").first.id)

City.create(name: "Portland", state_id: State.where(name: "Oregon").first.id)
City.create(name: "Oregon", state_id: State.where(name: "Oregon").first.id)
City.create(name: "Salem", state_id: State.where(name: "Oregon").first.id)
City.create(name: "Eugene", state_id: State.where(name: "Oregon").first.id)
City.create(name: "Gresham", state_id: State.where(name: "Oregon").first.id)
City.create(name: "Hillsboro", state_id: State.where(name: "Oregon").first.id)

City.create(name: "Philadelphia", state_id: State.where(name: "Pennsylvania").first.id)
City.create(name: "Pittsburgh", state_id: State.where(name: "Pennsylvania").first.id)
City.create(name: "Allentown", state_id: State.where(name: "Pennsylvania").first.id)
City.create(name: "Erie", state_id: State.where(name: "Pennsylvania").first.id)
City.create(name: "Reading", state_id: State.where(name: "Pennsylvania").first.id)
City.create(name: "Bethlehem", state_id: State.where(name: "Pennsylvania").first.id)

City.create(name: "Providence", state_id: State.where(name: "Rhode Island").first.id)
City.create(name: "Cranston", state_id: State.where(name: "Rhode Island").first.id)
City.create(name: "Warwick", state_id: State.where(name: "Rhode Island").first.id)
City.create(name: "Pawtucket", state_id: State.where(name: "Rhode Island").first.id)
City.create(name: "East Providence", state_id: State.where(name: "Rhode Island").first.id)

City.create(name: "Charlestown", state_id: State.where(name: "South Carolina").first.id)
City.create(name: "Columbia", state_id: State.where(name: "South Carolina").first.id)
City.create(name: "North Charleston", state_id: State.where(name: "South Carolina").first.id)
City.create(name: "Mount Pleasant", state_id: State.where(name: "South Carolina").first.id)
City.create(name: "Rock Hill", state_id: State.where(name: "South Carolina").first.id)

City.create(name: "Sioux Falls", state_id: State.where(name: "South Dakota").first.id)
City.create(name: "Rapid City", state_id: State.where(name: "South Dakota").first.id)
City.create(name: "Aberdeen", state_id: State.where(name: "South Dakota").first.id)
City.create(name: "Brookings", state_id: State.where(name: "South Dakota").first.id)
City.create(name: "Watertown", state_id: State.where(name: "South Dakota").first.id)

City.create(name: "Nashville", state_id: State.where(name: "Tennessee").first.id)
City.create(name: "Memphis", state_id: State.where(name: "Tennessee").first.id)
City.create(name: "Knoxville", state_id: State.where(name: "Tennessee").first.id)
City.create(name: "Chattanooga", state_id: State.where(name: "Tennessee").first.id)
City.create(name: "Clarksville", state_id: State.where(name: "Tennessee").first.id)
City.create(name: "Franklin", state_id: State.where(name: "Tennessee").first.id)

City.create(name: "Arlington", state_id: State.where(name: "Texas").first.id)
City.create(name: "Houston", state_id: State.where(name: "Texas").first.id)
City.create(name: "San Antonio", state_id: State.where(name: "Texas").first.id)
City.create(name: "Dallas", state_id: State.where(name: "Texas").first.id)
City.create(name: "Austin", state_id: State.where(name: "Texas").first.id)
City.create(name: "Fort Worth", state_id: State.where(name: "Texas").first.id)
City.create(name: "El Paso", state_id: State.where(name: "Texas").first.id)

City.create(name: "Salt Lake City", state_id: State.where(name: "Utah").first.id)
City.create(name: "West Valley City", state_id: State.where(name: "Utah").first.id)
City.create(name: "Provo", state_id: State.where(name: "Utah").first.id)
City.create(name: "West Jordan", state_id: State.where(name: "Utah").first.id)
City.create(name: "Orem", state_id: State.where(name: "Utah").first.id)

City.create(name: "Burlington", state_id: State.where(name: "Vermont").first.id)
City.create(name: "Essex", state_id: State.where(name: "Vermont").first.id)
City.create(name: "South Burlington", state_id: State.where(name: "Vermont").first.id)
City.create(name: "Colchester", state_id: State.where(name: "Vermont").first.id)
City.create(name: "Bennington", state_id: State.where(name: "Vermont").first.id)
City.create(name: "Rutland City", state_id: State.where(name: "Vermont").first.id)

City.create(name: "Virginia Beach", state_id: State.where(name: "Virginia").first.id)
City.create(name: "Norfolk", state_id: State.where(name: "Virginia").first.id)
City.create(name: "Chesapeake", state_id: State.where(name: "Virginia").first.id)
City.create(name: "Arlington", state_id: State.where(name: "Virginia").first.id)
City.create(name: "Richmond", state_id: State.where(name: "Virginia").first.id)
City.create(name: "Newport News", state_id: State.where(name: "Virginia").first.id)

City.create(name: "Seattle", state_id: State.where(name: "Washington").first.id)
City.create(name: "Spokane", state_id: State.where(name: "Washington").first.id)
City.create(name: "Tacoma", state_id: State.where(name: "Washington").first.id)
City.create(name: "Vancouver", state_id: State.where(name: "Washington").first.id)
City.create(name: "Bellevue", state_id: State.where(name: "Washington").first.id)
City.create(name: "Yakima", state_id: State.where(name: "Washington").first.id)

City.create(name: "Charleston", state_id: State.where(name: "West Virginia").first.id)
City.create(name: "Huntington", state_id: State.where(name: "West Virginia").first.id)
City.create(name: "Morgantown", state_id: State.where(name: "West Virginia").first.id)
City.create(name: "Parkersburg", state_id: State.where(name: "West Virginia").first.id)
City.create(name: "Wheeling", state_id: State.where(name: "West Virginia").first.id)

City.create(name: "Milwaukee", state_id: State.where(name: "Wisconsin").first.id)
City.create(name: "Madison", state_id: State.where(name: "Wisconsin").first.id)
City.create(name: "Green Bay", state_id: State.where(name: "Wisconsin").first.id)
City.create(name: "Kenosha", state_id: State.where(name: "Wisconsin").first.id)
City.create(name: "Appleton", state_id: State.where(name: "Wisconsin").first.id)
City.create(name: "Racine", state_id: State.where(name: "Wisconsin").first.id)
City.create(name: "Eau Claire", state_id: State.where(name: "Wisconsin").first.id)

City.create(name: "Cheyenne", state_id: State.where(name: "Wyoming").first.id)
City.create(name: "Casper", state_id: State.where(name: "Wyoming").first.id)
City.create(name: "Laramie", state_id: State.where(name: "Wyoming").first.id)
City.create(name: "Gillette", state_id: State.where(name: "Wyoming").first.id)
City.create(name: "Rock Springs", state_id: State.where(name: "Wyoming").first.id)
City.create(name: "Sheridan", state_id: State.where(name: "Wyoming").first.id)
City.create(name: "Green River", state_id: State.where(name: "Wyoming").first.id)


puts "#{State.count} states and #{City.count} cities seeded into the database."